apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:files-frontend-svc
  annotations:
    provider-registry-ref: user-space-{{ .Values.bfl.username }}/files
    provider-service-ref: files-service.os-framework:80
rules:
- nonResourceURLs: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:files-frontend-domain
  annotations:
    provider-registry-ref: {{ .Values.bfl.username }}/files
    provider-service-ref: files-service.os-framework:80
rules:
- nonResourceURLs: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:files-frontend-domain-settings
  annotations:
    provider-registry-ref: {{ .Values.bfl.username }}/settings
    provider-service-ref: files-service.os-framework:80
rules:
- nonResourceURLs: 
  - "/api/resources/*"
  - "/api/nodes/*"
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.bfl.username }}:files-provider-svc
  annotations:
    provider-registry-ref: user-system-{{ .Values.bfl.username }}/files
    provider-service-ref: files-service.os-framework:80
rules:
- nonResourceURLs: 
  - "/provider/query_file"
  - "/provider/get_search_folder_status"
  - "/provider/update_search_folder_paths"
  - "/provider/get_dataset_folder_status"
  - "/provider/update_dataset_folder_paths"
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user:{{ .Values.bfl.username }}:files-frontend-svc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.bfl.username }}:files-frontend-svc
subjects:
- kind: User
  name: '{{ .Values.bfl.username }}'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user:{{ .Values.bfl.username }}:files-frontend-domain
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.bfl.username }}:files-frontend-domain
subjects:
- kind: User
  name: '{{ .Values.bfl.username }}'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user:{{ .Values.bfl.username }}:files-frontend-domain-settings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.bfl.username }}:files-frontend-domain-settings
subjects:
- kind: User
  name: '{{ .Values.bfl.username }}'


---
apiVersion: v1
kind: Service
metadata:
  name: files
  namespace: user-space-{{ .Values.bfl.username }}
spec:
  type: ExternalName
  externalName: system-server.user-system-{{ .Values.bfl.username }}.svc.cluster.local
  ports:
    - protocol: TCP
      port: 28080
      targetPort: 28080
